name: model-organization-docs
channels:
    - chilipp/label/dev
    - conda-forge
dependencies:
    - python=3.6
    - matplotlib
    - numpy
    - sphinx
    - seaborn
    - ipython
    - jupyter_client
    - sphinx-argparse
    - pip:
        - autodocsumm
