name: model-organization-docs
dependencies:
    - python=3.5
    - matplotlib
    - numpy
    - sphinx
    - seaborn
    - ipython
    - jupyter_client
    - pip:
        - autodocsumm
        - sphinx-argparse==0.1.17
